import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Provider";
const inter = Inter({ subsets: ["latin"] });
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: "Qumail",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
